---
version: '3'

services:
  fosspay:
    build:
      context: .
      dockerfile: Dockerfile
    image: fosspay
    restart: unless-stopped
    volumes:
      - "./db/:/usr/src/app/db/"
      - "./config.ini:/usr/src/app/config.ini"
    command: gunicorn app:app -b 0.0.0.0:5000
    networks:
      - external
    ports:
     - "127.0.0.1:5000:5000"

networks:
  internal:
    internal: true
  external:
    driver: bridge
    
